# This is a config for E2B sandbox template.
# You can use template ID (kgb67pex8no88mhj7ycx) or template name (expo-react-native) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("expo-react-native") # Sync sandbox
# sandbox = await AsyncSandbox.create("expo-react-native") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('expo-react-native')

memory_mb = 1_024
cpu_count = 2
start_cmd = "cd /home/user && npm start"
dockerfile = "e2b.Dockerfile"
template_name = "expo-react-native"
template_id = "kgb67pex8no88mhj7ycx"
